# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Test fetching packages

on: [push]

jobs:
  fetch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        action:
          - "pip install git+https://github.com/kagekirin/metagen-py.git"
          - "pip install https://github.com/kagekirin/metagen-py/tarball/main"
          - "npm install -g git+https://git@github.com/kagekirin/metagen-js.git"
          - "npm install -g https://github.com/kagekirin/metagen-js/tarball/main"
          - "cargo install --branch main --git https://github.com/kagekirin/metagen-rs.git"
          - |
            dotnet tool install -g paket;
            echo 'git https://github.com/kagekirin/metagen-cs.git main build: "dotnet publish -f net5.0 -r linux-x64 -c Release --self-contained true"' > paket.dependencies;
            paket install
    steps:
      - name: fetch
        run: ${{ matrix.action }}
      - name: version
        run: |
          which metagen
          metagen --help
      - name: create some files
        run: |
          echo "important stuff" > README.md
          touch foo.bar
          touch baz
      - name: list files before run
        run: ls
      - name: test single file
        run: metagen -s test.foobar README.md
      - name: list files after 1st run
        run: ls
      - name: test file globbing
        run: metagen -s test.foobar *
      - name: list files after glob run
        run: ls
      - name: verify generated meta files
        run: |
          cat README.md.meta
          cat *.meta
