# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Test fetching packages

on: [push]

jobs:
  pip-git:
    runs-on: ubuntu-latest
    steps:
      - name: fetch git
        run: pip install git+https://github.com/kagekirin/metagen-py.git
      - name: version
        run: |
          which metagen
          cat `which metagen`
          metagen --help
      - name: test
        run: |
          ls
          metagen -s test.foobar README.md
          ls
          cat README.md.meta
      - name: test glob
        run: |
          ls
          metagen -s test.foobar *
          ls
          cat *.meta
  pip-tar:
    runs-on: ubuntu-latest
    steps:
      - name: fetch tarball
        run: pip install https://github.com/kagekirin/metagen-py/tarball/main
      - name: version
        run: |
          which metagen
          cat `which metagen`
          metagen --help
      - name: test
        run: |
          ls
          metagen -s test.foobar README.md
          ls
          cat README.md.meta
      - name: test glob
        run: |
          ls
          metagen -s test.foobar *
          ls
          cat *.meta

  npm-git:
    runs-on: ubuntu-latest
    steps:
      - name: fetch git
        run: npm install -g git+https://git@github.com/kagekirin/metagen-js.git
      - name: version
        run: |
          which metagen
          cat `which metagen`
          metagen --help
      - name: test
        run: |
          ls
          metagen -s test.foobar README.md
          ls
          cat README.md.meta
      - name: test glob
        run: |
          ls
          metagen -s test.foobar *
          ls
          cat *.meta
  npm-tar:
    runs-on: ubuntu-latest
    steps:
      - name: fetch tarball
        run: npm install -g https://github.com/kagekirin/metagen-js/tarball/main
      - name: version
        run: |
          which metagen
          cat `which metagen`
          metagen --help
      - name: test
        run: |
          ls
          metagen -s test.foobar README.md
          ls
          cat README.md.meta
      - name: test glob
        run: |
          ls
          metagen -s test.foobar *
          ls
          cat *.meta
