# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Fetch Test

on: [push]

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:

      - name: Fetch latest release info
        id: fetch-latest-release
        uses: thebritican/fetch-latest-release@v1
        with:
          github_token: ${{ github.token }}
      - name: Display latest release info
        run: |
          echo ${{ steps.fetch-latest-release.outputs.name }}
          echo ${{ steps.fetch-latest-release.outputs.tag_name }}
          echo ${{ steps.fetch-latest-release.outputs.url }}
          echo ${{ steps.fetch-latest-release.outputs.assets_url }}

      - name: Fetch latest release info (2)
        id: relinfos
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: KageKirin
          repo: metagen-rs
          excludes: prerelease, draft
      - name: Display latest release info (2)
        run: |
            echo ${{ steps.relinfos.outputs.release }}

      - name: Fetch release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "KageKirin/metagen-rs"
          #version: "tags/v0.1.18" latest
          file: "metagen.tar.gz"
          target: "metagen.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Unpack
        run: |
          ls *
          tar tvf metagen.tar.gz
          tar xvfp metagen.tar.gz --strip 3
          ls *
      - name: Test run
        run: ./metagen --help
